# Generated by Django 5.1.5 on 2025-07-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='brn',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
