# Generated by Django 5.1.5 on 2025-02-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucherrequest',
            old_name='ammout',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='voucherrequest',
            old_name='vouhers_expiry_date',
            new_name='vouchers_expiry_date',
        ),
    ]
