# Generated by Django 5.1.5 on 2025-05-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
