# Generated by Django 5.1.5 on 2025-02-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrails',
            name='action',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='audittrails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audittrails',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audittrails',
            name='table_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
