# Generated by Django 5.1.5 on 2025-01-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_alter_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='redeem_on',
            new_name='redeemed_on',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_status',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('issued', 'Issued'), ('expired', 'Expired'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled')], default='provisional', max_length=20),
        ),
        migrations.DeleteModel(
            name='PendingVoucher',
        ),
    ]
