# Generated by Django 5.1.5 on 2025-02-25 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_rename_ammout_voucherrequest_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherrequest',
            name='vouchers_expiry_date',
        ),
        migrations.AddField(
            model_name='voucherrequest',
            name='validity',
            field=models.IntegerField(blank=True, default=1, help_text='Maximum validity period (1 to 12 months or weeks)', null=True, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='voucherrequest',
            name='validity_type',
            field=models.CharField(choices=[('week', 'Week'), ('month', 'Month')], default='week', help_text="Type of validity, either 'week' or 'month'", max_length=5),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
