# Generated by Django 5.1.5 on 2025-01-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0003_rename_redeem_on_voucher_redeemed_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
