# Generated by Django 5.1.5 on 2025-02-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0003_remove_voucherrequest_vouchers_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucherrequest',
            old_name='validity',
            new_name='validity_periode',
        ),
    ]
