# Generated by Django 5.1.5 on 2025-03-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0004_rename_validity_voucherrequest_validity_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
