# Generated by Django 5.1.5 on 2025-01-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0004_alter_client_contact_alter_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherrequest',
            name='quantity_of_vouchers',
            field=models.IntegerField(default=1),
        ),
    ]
