# Generated by Django 5.1.5 on 2025-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0005_voucherrequest_quantity_of_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_ref',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voucherrequest',
            name='request_ref',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
