# Generated by Django 5.1.5 on 2025-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0005_client_company_address_client_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='prefix',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
