# Generated by Django 5.1.5 on 2025-01-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0006_alter_voucher_voucher_ref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucherrequest',
            old_name='user',
            new_name='captured_by',
        ),
    ]
