# Generated by Django 5.1.5 on 2025-01-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0007_rename_user_voucherrequest_captured_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucherrequest',
            old_name='captured_by',
            new_name='recorded_by',
        ),
    ]
