# Generated by Django 5.1.5 on 2025-01-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0008_rename_captured_by_voucherrequest_recorded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucherrequest',
            old_name='date_time_captured',
            new_name='date_time_recorded',
        ),
    ]
