# Generated by Django 5.1.5 on 2025-01-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0009_rename_date_time_captured_voucherrequest_date_time_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_voucher_requests', to='vms_app.client'),
        ),
    ]
