# Generated by Django 5.1.5 on 2025-01-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0010_alter_voucherrequest_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='created_at',
            new_name='date_time_created',
        ),
    ]
