# Generated by Django 5.1.5 on 2025-01-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0011_rename_created_at_voucher_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrequest',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_voucher_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
