# Generated by Django 5.1.5 on 2025-01-23 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0013_alter_voucherrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrequest',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_voucher_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
