# Generated by Django 5.1.5 on 2025-01-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0014_alter_voucherrequest_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='extention_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='redeemed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
