# Generated by Django 5.1.5 on 2025-01-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0015_alter_voucher_extention_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='addresse',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
