# Generated by Django 5.1.5 on 2025-01-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0016_shop_addresse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittrails',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', 'email']},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['voucher_ref']},
        ),
        migrations.AlterModelOptions(
            name='voucherrequest',
            options={'ordering': ['request_ref']},
        ),
    ]
