# Generated by Django 5.1.5 on 2025-01-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0017_alter_audittrails_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='redeemed_on',
        ),
        migrations.AddField(
            model_name='voucher',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
