# Generated by Django 5.1.5 on 2025-01-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0018_remove_voucher_redeemed_on_voucher_redeemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
