# Generated by Django 5.1.5 on 2025-01-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0019_voucherrequest_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='addresse',
            new_name='address',
        ),
    ]
