# Generated by Django 5.1.5 on 2025-01-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0020_rename_addresse_shop_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='redeemed',
        ),
    ]
