# Generated by Django 5.1.5 on 2025-01-30 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0021_remove_voucher_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrails',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 1, 30, 6, 57, 4, 761370, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='redemption_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 1, 30, 6, 57, 4, 761370, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date_time_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 1, 30, 6, 57, 4, 761370, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucherrequest',
            name='date_time_recorded',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2025, 1, 30, 6, 57, 4, 761370, tzinfo=datetime.timezone.utc)),
        ),
    ]
