# Generated by Django 5.1.5 on 2025-01-30 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0023_alter_audittrails_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrails',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 7, 39, 3, 455246, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='redemption_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 7, 39, 3, 455246, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date_time_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 7, 39, 3, 455246, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucherrequest',
            name='date_time_recorded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 30, 7, 39, 3, 455246, tzinfo=datetime.timezone.utc)),
        ),
    ]
