# Generated by Django 5.1.5 on 2025-02-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0025_alter_audittrails_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='redemption_infos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_voucher', to='vms_app.redemption'),
        ),
    ]
