# Generated by Django 5.1.5 on 2025-02-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0026_voucher_redemption_infos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='redemption_infos',
        ),
    ]
