# Generated by Django 5.1.5 on 2025-02-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0027_remove_voucher_redemption_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption',
            name='voucher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redemption', to='vms_app.voucher'),
        ),
    ]
