# Generated by Django 5.1.5 on 2025-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0028_alter_redemption_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption',
            name='till_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
