# Generated by Django 5.1.5 on 2025-02-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0030_alter_voucherrequest_request_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['voucher_ref'], 'permissions': [('can_redeem_voucher', 'Can redeem voucher')]},
        ),
        migrations.AlterModelOptions(
            name='voucherrequest',
            options={'ordering': ['request_ref'], 'permissions': [('can_reject_request', 'Can reject a voucher request'), ('can_approve_request', 'Can approve a voucher request'), ('can_change_to_paid', 'Can change the request_status from pending to paid')]},
        ),
    ]
