# Generated by Django 5.1.5 on 2025-02-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0031_alter_voucher_options_alter_voucherrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['voucher_ref'], 'permissions': [('redeem_voucher', 'Can redeem voucher')]},
        ),
        migrations.AlterModelOptions(
            name='voucherrequest',
            options={'ordering': ['request_ref'], 'permissions': [('reject_request', 'Can reject a voucher request'), ('approve_request', 'Can approve a voucher request'), ('change_to_paid', 'Can change the request_status from pending to paid')]},
        ),
    ]
